/**
 * ============================================================
 *  SAJEEL IQBAL — PORTFOLIO PROJECTS DATA
 * ============================================================
 *  HOW TO ADD A NEW PROJECT:
 *
 *  1. Find the correct category array below (e.g. socialMedia, emailMarketing, etc.)
 *  2. Copy an existing project object and paste it at the TOP of the array
 *     (newest projects should appear first)
 *  3. Fill in your details — see field descriptions below
 *  4. For media, use one of these types per item:
 *       { type: "image",    src: "path/to/image.jpg",   caption: "..." }
 *       { type: "video",    src: "path/to/video.mp4",   caption: "..." }
 *       { type: "youtube",  src: "https://youtu.be/ID", caption: "..." }
 *       { type: "audio",    src: "path/to/audio.mp3",   caption: "..." }
 *       { type: "carousel", items: [ {src, caption}, ... ] }
 *       { type: "embed",    src: "https://...",          caption: "..." }
 *  5. Save the file — your new project appears automatically.
 * ============================================================
 */

const PROJECTS = {

  // ── SOCIAL MEDIA STRATEGY ──────────────────────────────────
  socialMedia: {
    pageTitle: "Social Media Strategy",
    pageSubtitle: "Building audiences, sparking conversations, and growing brands across platforms.",
    accentColor: "#C9941A",
    projects: [
      {
        id: "sm-001",
        title: "Brand Relaunch Campaign",
        client: "Lifestyle Brand",
        year: "2024",
        tags: ["Instagram", "TikTok", "LinkedIn", "Organic Growth"],
        summary: "Led the complete social media strategy for a rebranded lifestyle brand — growing organic reach by 240% over 6 months through targeted content pillars and influencer partnerships.",
        challenge: "The brand had a disjointed presence across platforms with inconsistent messaging and an audience that had disengaged post-rebrand. The goal was to reintroduce the brand, rebuild trust, and drive meaningful growth without paid spend.",
        approach: "Developed three distinct content pillars aligned with the new brand identity, created a 3-month editorial calendar, identified and briefed micro-influencers, and established a consistent visual language across all channels.",
        results: [
          { label: "Organic Reach", value: "+240%" },
          { label: "Follower Growth", value: "+18K" },
          { label: "Engagement Rate", value: "4.8%" },
          { label: "Influencer Partnerships", value: "12" }
        ],
        media: [
          {
            type: "carousel",
            caption: "Content grid samples from the relaunch campaign",
            items: [
              { src: "assets/sm-001-a.jpg", caption: "Brand identity post — Day 1 of relaunch" },
              { src: "assets/sm-001-b.jpg", caption: "Lifestyle content pillar sample" },
              { src: "assets/sm-001-c.jpg", caption: "Influencer collab deliverable" }
            ]
          },
          {
            type: "video",
            src: "assets/sm-001-reel.mp4",
            caption: "Hero reel produced for campaign launch"
          }
        ]
      },
      {
        id: "sm-002",
        title: "Executive LinkedIn Presence",
        client: "C-Suite Client",
        year: "2023",
        tags: ["LinkedIn", "Thought Leadership", "Personal Branding"],
        summary: "Developed and executed a LinkedIn thought leadership content strategy for a senior executive, growing their following from 800 to 12K+ in under a year.",
        challenge: "The client had significant expertise but no digital presence. Competitors in their industry were dominating the conversation online, and the client needed to establish authority quickly.",
        approach: "Conducted in-depth interviews to extract insights, built a content framework around 4 signature topics, and created a consistent weekly publishing cadence with original long-form posts, carousels, and short commentary.",
        results: [
          { label: "Follower Growth", value: "800 → 12K+" },
          { label: "Avg. Post Impressions", value: "8,500" },
          { label: "Profile Views (monthly)", value: "+340%" },
          { label: "Inbound Inquiries", value: "+22" }
        ],
        media: [
          {
            type: "image",
            src: "assets/sm-002-a.jpg",
            caption: "Sample LinkedIn carousel — 'The 5-Step Decision Framework'"
          },
          {
            type: "audio",
            src: "assets/sm-002-podcast.mp3",
            caption: "Guest podcast appearance generated by the LinkedIn strategy"
          }
        ]
      }
    ]
  },

  // ── EMAIL MARKETING ───────────────────────────────────────
  emailMarketing: {
    pageTitle: "Email Marketing",
    pageSubtitle: "Campaigns that land in inboxes — and stay in minds.",
    accentColor: "#C9941A",
    projects: [
      {
        id: "em-001",
        title: "Lead Nurture Sequence",
        client: "B2B Service Firm",
        year: "2024",
        tags: ["HubSpot", "Automation", "B2B", "Lead Nurturing"],
        summary: "Built a 7-email automated nurture campaign that increased lead-to-client conversion rates by 38% for a B2B professional services firm.",
        challenge: "The firm had strong inbound lead volume but a leaky funnel — leads were going cold within 2 weeks because there was no structured follow-up process beyond a single intro email.",
        approach: "Mapped the full buyer journey, identified key decision-making moments, and wrote a 7-touch sequence that educated, built trust, and prompted action at each stage. Set up the automation in HubSpot with behavioural triggers.",
        results: [
          { label: "Conversion Rate", value: "+38%" },
          { label: "Email Open Rate", value: "52%" },
          { label: "Click-Through Rate", value: "14%" },
          { label: "Leads Converted (Q1)", value: "27" }
        ],
        media: [
          {
            type: "image",
            src: "assets/em-001-flow.jpg",
            caption: "Automation flow map — 7-touch nurture sequence"
          },
          {
            type: "carousel",
            caption: "Email design samples from the sequence",
            items: [
              { src: "assets/em-001-email1.jpg", caption: "Email 1 — Welcome & Brand Story" },
              { src: "assets/em-001-email3.jpg", caption: "Email 3 — Social Proof + Case Study" },
              { src: "assets/em-001-email7.jpg", caption: "Email 7 — Final CTA" }
            ]
          }
        ]
      },
      {
        id: "em-002",
        title: "Monthly Newsletter Redesign",
        client: "Professional Association",
        year: "2023",
        tags: ["Mailchimp", "Design", "Content Strategy", "Retention"],
        summary: "Redesigned and re-strategised a monthly newsletter for a 6,000-member professional association, increasing open rates from 18% to 41%.",
        challenge: "The existing newsletter was text-heavy, poorly structured, and had been losing subscribers steadily. Members described it as 'easy to ignore.'",
        approach: "Audited all previous issues, surveyed members on content preferences, redesigned the template with clear hierarchy and visual interest, and restructured the content into scannable sections with distinct value propositions.",
        results: [
          { label: "Open Rate", value: "18% → 41%" },
          { label: "Click Rate", value: "3% → 11%" },
          { label: "Unsubscribe Rate", value: "−65%" },
          { label: "Member Satisfaction", value: "+4.2 / 5" }
        ],
        media: [
          {
            type: "image",
            src: "assets/em-002-before.jpg",
            caption: "Before: Original newsletter template"
          },
          {
            type: "image",
            src: "assets/em-002-after.jpg",
            caption: "After: Redesigned newsletter template"
          }
        ]
      }
    ]
  },

  // ── CONTENT STRATEGY ──────────────────────────────────────
  contentStrategy: {
    pageTitle: "Content Strategy",
    pageSubtitle: "Every word deliberate. Every piece of content, a strategy.",
    accentColor: "#C9941A",
    projects: [
      {
        id: "cs-001",
        title: "Thought Leadership Programme",
        client: "C-Suite Executive",
        year: "2024",
        tags: ["LinkedIn", "Blog", "Long-Form", "Personal Brand"],
        summary: "Developed and executed a 12-month content programme positioning a senior executive as an industry thought leader, resulting in 12K+ followers and 3 speaking invitations.",
        challenge: "Starting from near-zero digital presence, the objective was to establish authentic authority in a competitive professional space without the content feeling ghostwritten or generic.",
        approach: "Ran monthly 'insight extraction' sessions, developed a signature content framework, produced long-form articles, short-form posts, and carousel content, and built a repeatable editorial system the client could maintain independently.",
        results: [
          { label: "Followers Gained", value: "12K+" },
          { label: "Speaking Invitations", value: "3" },
          { label: "Media Mentions", value: "5" },
          { label: "Avg. Monthly Reach", value: "85K" }
        ],
        media: [
          {
            type: "carousel",
            caption: "Content samples from the thought leadership programme",
            items: [
              { src: "assets/cs-001-a.jpg", caption: "LinkedIn carousel — 'Leadership in Uncertainty'" },
              { src: "assets/cs-001-b.jpg", caption: "Long-form article header design" },
              { src: "assets/cs-001-c.jpg", caption: "Speaking event promo content" }
            ]
          },
          {
            type: "video",
            src: "assets/cs-001-talk.mp4",
            caption: "Conference keynote — generated through content programme visibility"
          }
        ]
      },
      {
        id: "cs-002",
        title: "Website Content Overhaul",
        client: "Professional Services Firm",
        year: "2023",
        tags: ["Web Copy", "SEO", "UX Writing", "Brand Voice"],
        summary: "Rewrote the entire website (18 pages) for a mid-sized professional services firm, improving organic traffic by 67% and reducing bounce rate by 34% within 3 months.",
        challenge: "The firm's website was full of industry jargon, had no clear value proposition, and was not optimised for search. Visitors were leaving within seconds.",
        approach: "Conducted stakeholder interviews and competitor analysis, developed a new brand voice guide, wrote all pages from scratch with SEO-informed structure, clear CTAs, and human-first language.",
        results: [
          { label: "Organic Traffic", value: "+67%" },
          { label: "Bounce Rate", value: "−34%" },
          { label: "Pages Written", value: "18" },
          { label: "Avg. Session Duration", value: "+1m 42s" }
        ],
        media: [
          {
            type: "image",
            src: "assets/cs-002-homepage.jpg",
            caption: "Homepage before & after content restructure"
          }
        ]
      }
    ]
  },

  // ── INTEGRATED CAMPAIGNS ──────────────────────────────────
  integratedCampaigns: {
    pageTitle: "Integrated Campaigns",
    pageSubtitle: "Multi-channel campaigns where every touchpoint tells the same story.",
    accentColor: "#C9941A",
    projects: [
      {
        id: "ic-001",
        title: "Product Launch — Multi-Channel",
        client: "Consumer Brand",
        year: "2024",
        tags: ["Paid Social", "PR", "Email", "Events", "Launch"],
        summary: "Coordinated a full product launch spanning paid social, email, PR outreach, and event marketing — achieving 150% of first-month sales targets and press coverage in 3 industry publications.",
        challenge: "The launch window was 6 weeks, the budget was mid-range, and the product was entering a crowded category. The campaign needed to drive both awareness and immediate conversion simultaneously.",
        approach: "Built a phased launch plan: 2-week pre-launch teaser (email + organic social), 1-week launch blitz (paid ads + PR + launch event), 3-week post-launch sustain (retargeting + community content). Every channel had a distinct role and shared visual identity.",
        results: [
          { label: "Sales Target", value: "150% achieved" },
          { label: "Press Coverage", value: "3 publications" },
          { label: "Email Revenue", value: "£28K" },
          { label: "ROAS (Paid Social)", value: "4.2×" }
        ],
        media: [
          {
            type: "video",
            src: "assets/ic-001-launch.mp4",
            caption: "Hero launch video — hero asset for all paid and organic channels"
          },
          {
            type: "carousel",
            caption: "Campaign creative across channels",
            items: [
              { src: "assets/ic-001-ad1.jpg", caption: "Paid social — teaser phase ad" },
              { src: "assets/ic-001-ad2.jpg", caption: "Launch day hero ad" },
              { src: "assets/ic-001-event.jpg", caption: "Launch event setup" },
              { src: "assets/ic-001-press.jpg", caption: "Press feature — Industry Publication" }
            ]
          },
          {
            type: "image",
            src: "assets/ic-001-strategy.jpg",
            caption: "Campaign architecture overview"
          }
        ]
      },
      {
        id: "ic-002",
        title: "Awareness to Advocacy Programme",
        client: "Non-Profit Organisation",
        year: "2023",
        tags: ["Social", "Email", "Community", "Video", "Non-Profit"],
        summary: "Designed and executed a 3-month integrated awareness campaign for a non-profit that grew their donor base by 44% and raised £60K through a combined digital and community approach.",
        challenge: "The organisation had strong community support locally but very limited digital presence. They needed to translate in-person goodwill into online engagement and tangible donations.",
        approach: "Produced a 3-part mini documentary series shared across social and YouTube, paired with a targeted email campaign to existing supporters and a community ambassador programme to amplify reach organically.",
        results: [
          { label: "Donor Base Growth", value: "+44%" },
          { label: "Funds Raised", value: "£60K" },
          { label: "Video Views", value: "120K+" },
          { label: "New Email Subscribers", value: "+3,200" }
        ],
        media: [
          {
            type: "youtube",
            src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
            caption: "Mini-documentary Episode 1 — 'The People Behind the Mission'"
          },
          {
            type: "carousel",
            caption: "Campaign visuals and social content",
            items: [
              { src: "assets/ic-002-social1.jpg", caption: "Awareness phase social content" },
              { src: "assets/ic-002-social2.jpg", caption: "Donor spotlight post" },
              { src: "assets/ic-002-email.jpg", caption: "Email campaign header design" }
            ]
          }
        ]
      }
    ]
  }
};
